import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import { CartProvider } from "@/components/Panier/Context/CartContext";

import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer";
import { Toaster } from "@/components/shared/Sonner";
import CodePromo from "@/components/shared/CodePromo";
import { initializeServerTasks } from "@/lib/cron";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Téléphone du Monde",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  let cronInitialized = false;

  if (typeof window === "undefined" && !cronInitialized) {
    initializeServerTasks(); // Initialise le cron
    cronInitialized = true; // Empêche plusieurs initialisations
  }

  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-noir-900 min-h-screen`}
      >
        <SessionProvider session={session}>
          <CartProvider>
            <CodePromo />
            <Header />
            <div className="min-h-screen">
              {children} <Toaster />
            </div>
            <Footer />
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
