/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import { CartProvider } from "@/components/Panier/Context/CartContext";

import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer";
import { Toaster } from "@/components/shared/Sonner";
import CodePromo from "@/components/shared/CodePromo";
import { initializeServerTasks } from "@/lib/cron";
// import CookieConsentWrapper from "@/components/shared/CookieConsentWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Téléphone du Monde",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  let cronInitialized = false;

  if (typeof window === "undefined" && !cronInitialized) {
    initializeServerTasks(); // Initialise le cron
    cronInitialized = true; // Empêche plusieurs initialisations
  }

  return (
    <html lang="fr">
      <head>
        <script>
          {`
           !function (w, d, t) {
  w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie","holdConsent","revokeConsent","grantConsent"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(
var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var r="https://analytics.tiktok.com/i18n/pixel/events.js",o=n&&n.partner;ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=r,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};n=document.createElement("script")
;n.type="text/javascript",n.async=!0,n.src=r+"?sdkid="+e+"&lib="+t;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(n,e)};


  ttq.load('CUCJ7EBC77UC80LSJ65G');
  ttq.page();
}(window, document, 'ttq');
`}
        </script>

        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="1439cf05-e33d-4e94-8cef-d0b68baf109c"
        ></script>

        <link
          rel="icon"
          type="image/png"
          href="/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-noir-900 min-h-screen`}
      >
        <SessionProvider session={session}>
          <CartProvider>
            <CodePromo />
            <Header />
            <div className="min-h-screen">
              {children} <Toaster />
            </div>
            <Footer />
          </CartProvider>
        </SessionProvider>
        {/* <CookieConsentWrapper /> */}
      </body>
    </html>
  );
}
